name: Crowdin / Upload translations

on:
  push:
    branches:
      - 'main'
      - 'stable-*'
    paths:
      - crowdin-glitch.yml
      - app/javascript/flavours/glitch/locales/en.json
      - config/locales-glitch/en.yml
      - config/locales-glitch/simple_form.en.yml
      - config/locales-glitch/activerecord.en.yml
      - config/locales-glitch/devise.en.yml
      - config/locales-glitch/doorkeeper.en.yml
      - .github/workflows/crowdin-upload.yml

jobs:
  upload-translations:
    runs-on: ubuntu-latest
    if: github.repository == 'glitch-soc/mastodon'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          config: crowdin-glitch.yml
          upload_sources: true
          upload_translations: false
          download_translations: false
          crowdin_branch_name: ${{ github.base_ref || github.ref_name }}

        env:
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
